// @generated by `make rust` — do not edit by hand.
//
// Each OCPI version's generated types are exposed as a module. The source files
// are named after the schema version (e.g. v2.1.1.rs), which is not a valid
// Rust identifier, so they are mapped to underscore module names via #[path].
#![allow(non_camel_case_types, dead_code, clippy::all)]

#[path = "v2.1.1.rs"]
pub mod v2_1_1;
#[path = "v2.2.1.rs"]
pub mod v2_2_1;
#[path = "v2.3.0.rs"]
pub mod v2_3_0;
#[path = "v2.3.0-bookings.rs"]
pub mod v2_3_0_bookings;
#[path = "v2.3.0-payments.rs"]
pub mod v2_3_0_payments;
